name: build

on: [push]

jobs:
  build:
    timeout-minutes: 3
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [18, 20, 22]

    steps:
    - uses: actions/checkout@v4
    - name: Install Chrome
      uses: browser-actions/setup-chrome@latest
    - name: Using Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - name: Upload Code Coverage
      if: ${{ matrix.node-version == '22' && matrix.os == 'ubuntu-latest' }}
      uses: codecov/codecov-action@v4
      with:
        files: ./coverage/coverage-final.json
        token: ${{ secrets.CODECOV_TOKEN }}
